Traceback (most recent call last):
  File "/seamless/seamless/silk/Silk.py", line 772, in __getattribute__
    return super().__getattribute__("_get_special")(attr)
  File "/seamless/seamless/silk/Silk.py", line 709, in _get_special
    data2 = RichValue(self._data).value
  File "/seamless/seamless/silk/Silk.py", line 47, in __init__
    value = value._unwrap()
  File "/seamless/seamless/mixed/__init__.py", line 44, in _unwrap
    return FormWrapper(self.value, self.form, self.storage)
  File "/seamless/seamless/mixed/__init__.py", line 68, in __getattr__
    return self.__getitem__(attr)
  File "/seamless/seamless/mixed/__init__.py", line 91, in __getitem__
    raise TypeError(type(value))
TypeError: <class 'int'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "structured_cell/schema.py", line 65, in <module>
    print(s.x.data)
  File "/seamless/seamless/silk/Silk.py", line 784, in __getattribute__
    result = RichValue(result).value
  File "/seamless/seamless/silk/Silk.py", line 47, in __init__
    value = value._unwrap()
  File "/seamless/seamless/mixed/__init__.py", line 44, in _unwrap
    return FormWrapper(self.value, self.form, self.storage)
  File "/seamless/seamless/mixed/__init__.py", line 68, in __getattr__
    return self.__getitem__(attr)
  File "/seamless/seamless/mixed/__init__.py", line 91, in __getitem__
    raise TypeError(type(value))
TypeError: <class 'int'>
